// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyYq_3h-25-It2jfdL9UNql_sx3eI-d7U',
    appId: '1:376529838985:web:16e37038b78cebc4573758',
    messagingSenderId: '376529838985',
    projectId: 'test-730db',
    authDomain: 'test-730db.firebaseapp.com',
    storageBucket: 'test-730db.appspot.com',
    measurementId: 'G-H58GPGMTDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxWDzvQY-QG-wmnzQ_IxDcVo8vIgRCy4',
    appId: '1:376529838985:android:a21d04c89167a1c5573758',
    messagingSenderId: '376529838985',
    projectId: 'test-730db',
    storageBucket: 'test-730db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6AWArX1fowFwUrtjVGh-VvErKMYZShX8',
    appId: '1:376529838985:ios:392a212a6452b586573758',
    messagingSenderId: '376529838985',
    projectId: 'test-730db',
    storageBucket: 'test-730db.appspot.com',
    iosClientId:
        '376529838985-99c6vu66ruato9c7kk2vcqqndisj1c0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.workList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6AWArX1fowFwUrtjVGh-VvErKMYZShX8',
    appId: '1:376529838985:ios:392a212a6452b586573758',
    messagingSenderId: '376529838985',
    projectId: 'test-730db',
    storageBucket: 'test-730db.appspot.com',
    iosClientId:
        '376529838985-99c6vu66ruato9c7kk2vcqqndisj1c0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.workList',
  );
}
